// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfWtnGeksklJ1zc6rUBITuHtExFX7YOtE',
    appId: '1:579794701265:web:638f926f9b9bd944cceef0',
    messagingSenderId: '579794701265',
    projectId: 'moodtrackproj',
    authDomain: 'moodtrackproj.firebaseapp.com',
    storageBucket: 'moodtrackproj.firebasestorage.app',
    measurementId: 'G-8VSNB7D94F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTkqdVC1Cok0oBIgRy27PyxfAZIiduUfo',
    appId: '1:579794701265:android:a70596050fdacbbbcceef0',
    messagingSenderId: '579794701265',
    projectId: 'moodtrackproj',
    storageBucket: 'moodtrackproj.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfWtnGeksklJ1zc6rUBITuHtExFX7YOtE',
    appId: '1:579794701265:web:a0b37db1a0708673cceef0',
    messagingSenderId: '579794701265',
    projectId: 'moodtrackproj',
    authDomain: 'moodtrackproj.firebaseapp.com',
    storageBucket: 'moodtrackproj.firebasestorage.app',
    measurementId: 'G-EYF1BNZR5X',
  );
}
